site_name: "Documentação Thermo"
nav:
  - Introdução: index.md
  - Repositórios: repositorios.md
  - Arquitetura:
      - Documento de Arquitetura de Software: arquitetura/documento-arquitetura.md
  - Modelagem:
      - Driagrama de Classes: modelagem/diagrama-classes.md
  - Planejamento:
      - Documento de visão: planejamento/documento-visao.md
      - Brainstorm: planejamento/brainstorm.md
      - Requisitos: planejamento/documento-requisitos.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: dark blue
      accent: light blue

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      accent: blue

      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - include-markdown
